// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;

import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;

import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.JavascriptExecutor;
import java.util.*;
public class PruebaTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    System.setProperty("webdriver.chrome.driver", "src/main/resources/chromedriver.exe");

    driver = new ChromeDriver();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void prueba() {
    driver.get("http://automationpractice.com/index.php?controller=my-account");
    driver.manage().window().setSize(new Dimension(1936, 1056));
    driver.findElement(By.id("email")).click();
    driver.findElement(By.id("email")).sendKeys("micaela.tosini.89@gmail.com");
    driver.findElement(By.id("passwd")).sendKeys("Castiel89");
    driver.findElement(By.cssSelector("#SubmitLogin > span")).click();
    driver.findElement(By.linkText("Contact us")).click();
    driver.findElement(By.id("id_contact")).click();
    {
      WebElement dropdown = driver.findElement(By.id("id_contact"));
      dropdown.findElement(By.xpath("//option[. = 'Customer service']")).click();
    }
    driver.findElement(By.id("id_contact")).click();
    driver.findElement(By.name("id_order")).click();
    driver.findElement(By.name("id_order")).click();
    driver.findElement(By.id("message")).click();
    driver.findElement(By.id("message")).sendKeys("mensaje de prueba.");
    driver.findElement(By.cssSelector("#submitMessage > span")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".alert"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).clickAndHold().perform();
    }
    {
      WebElement element = driver.findElement(By.id("center_column"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.id("center_column"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).release().perform();
    }
    driver.findElement(By.cssSelector(".alert")).click();
    assertThat(driver.getTitle(), is("Contact us - My Store"));
    assertThat(driver.findElement(By.cssSelector(".alert")).getText(), is("Your message has been successfully sent to our team."));
  }
}
